### ISSUE TITLE
Visual editor drag points overlap with text

### ISSUE THREAD

**Issue by gparmeggiani** [likec4/likec4#1104]
I started to use the awesome layout editor. It's great, however I found a little annoyance.
Sometimes the drag points overlap with the relationship labels, making it impossible to drag them. See here:  

![image](https://github.com/user-attachments/assets/509aa01c-77cf-4a96-b6d9-8b88f3dbb665)

**Comment by pavelpykhtin** [comment]
Hi, @gparmeggiani !

Thank you for feedback! I agree it is quite annoying issue. There is a workaround: if you select the edge, the label will be moved to the back, and you'll be able to drag the control point.

As far as I can see this can't be fixed without breaking current behavior "bring edge label to front on hover":
- A control point is a part of an edge
- Edges are always under elements (edge zIndex is 4 vs 6 of element, and both values are constants in xyflow). 
- An edge label must be placed under the control point in order to be draggable. 
Thus, edge labels must be placed under the edges and nodes.

@davydkov , what do you think about this issue? What is more valuable: consistent drag behavior of control points or  "bring edge label to front on hover" behavior?

**Comment by davydkov** [comment]
I think drag behavior of control points is more valuable for the editor.

I started once with allowing to turn off/on editing state right in the preview panel (not via extension settings). But it is incomplete.

I think this may enhance overall experience.

**Comment by gparmeggiani** [comment]
what about allowing to drag and reposition the label? It would both fix the issue and add a quite useful feature
