### ISSUE TITLE
Custom colors not working as documented

### ISSUE THREAD

**Issue by rumpelrausch** [likec4/likec4#1212]
https://likec4.dev/dsl/specification/#color tells how to use custom rgbhex colors.
It looks as though they get shifted to the next pre-defined color.

I tried with `#100`, `#200`, `#300` and so on and the result is always `#f9403b`.
I tried in VSCode, playground and static build: Same results.

Is this a bug or did I miss something?

#keywords colour srgb

**Comment by pavelpykhtin** [comment]
Hi, @rumpelrausch!

It's an intended behavior. The reason is that to draw a node, we need not only fill color, but also border color and text color. Same with the color of edge - line color, label background color and text color are required.
Thus, the color pallet generator from mantine library is used to build a color scheme from the provided base color.

**Comment by rumpelrausch** [comment]
Understood, thanks.
For reference: You might want to start here: https://mantine.dev/colors-generator/
