### ISSUE TITLE
Quick button View Relationships not showing

### ISSUE THREAD

**Issue by viktorgusev1984** [likec4/likec4#1242]
<img width="238" alt="1" src="https://github.com/user-attachments/assets/1e1f8e5e-e989-4cf8-b2ed-71674d0d7499">

**Comment by pavelpykhtin** [comment]
Hi, @viktorgusev1984 !

It seems that it was intentional because this view accessible both from details dialog and from popup which shows on hover in editing mode.
I guess the problem is related to one of readonly modes (react component or webcomponent) right? Does the Relationships tab in Details dialog cover your scenario?

**Comment by viktorgusev1984** [comment]
Hi, @pavelpykhtin !
In the dialog box with details there is a button open, but it is too long way.
Quick button is much more convenient for viewing in out.
