### ISSUE TITLE
poor performance

### ISSUE THREAD

**Issue by gparmeggiani** [likec4/likec4#613]
I noticed that the frame rate can be quite poor, to the point that navigating through the views can become annoying.

Are you guys aware of this, is there any plan to improve the situation?

**Comment by davydkov** [comment]
Hi @gparmeggiani 

Yes, the issue does exist.

Please check the discussion here. https://github.com/likec4/likec4/discussions/600

**Comment by mcpride** [comment]
Hi @davydkov, 

I tested the newest prerelease version [v1.0.0-next.11](https://github.com/likec4/likec4/releases/tag/v1.0.0-next.11) and the performance looks promising! 👍 

Also the png export runs without failures as described in #634. Unfortunately I cannot use it as static images for our documents, because the labels of the relations on transparent background are too light and cannot be read. I hope, this can also be fixed easily.

**Comment by davydkov** [comment]
Hi @mcpride 

Thanks for the feedback! I'm planning to release this month.

Could you please try the `..next.13` and let me know how it goes?
I switched to the light theme by default (make an option later).

Like:
```
npx likec4@next export png -o pngnext13
```

**Comment by mcpride** [comment]
> Hi @mcpride
> 
> Thanks for the feedback! I'm planning to release this month.
> 
> Could you please try the `..next.13` and let me know how it goes? I switched to the light theme by default (make an option later).
> 
> Like:
> 
> ```
> npx likec4@next export png -o pngnext13
> ```

Hi @davydkov, yes .. the `next.13` fixes the described label readability problem in png export! Thanks!
