### ISSUE TITLE
Blurry Font

### ISSUE THREAD

**Issue by aelberg** [likec4/likec4#734]
Since upgrading to >1.0 the text on diagrams for the default rendering with React and the new Editor is blurry.  This is both running locally and when generating a static site.

If I change to React (pre 1.0) the font is sharp.

Let me know if a screenshot would be helpful.

**Comment by davydkov** [comment]
Hey @aelberg 

Could you please upload the screenshot?

**Comment by davydkov** [comment]
What happens if you disable this one?

<img width="303" alt="image" src="https://github.com/likec4/likec4/assets/824903/a93aaa35-834b-4888-bbf3-f48e3fddeeae">

[Here](https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome) reported this might cause the blur.

Also try to add `backface-visibility: hidden`.

Does it work?

**Comment by shadz3rg** [comment]
@davydkov Sadly nothing from this thread worked

**Comment by davydkov** [comment]
@shadz3rg @aelberg 

Can you try [v1.1.1](https://github.com/likec4/likec4/releases/tag/v1.1.1)?

**Comment by aelberg** [comment]
Confirmed the text is sharp in version 1.1.1 
However, at certain zoom levels when hovering over an element or relationship the text is blurry.  I see the same behavior in Chrome and Edge browsers.
I tried with the example DSL from the getting started page (https://likec4.dev/docs/) and was not able to replicate the behavior.

![Screenshot 2024-05-28 062335](https://github.com/likec4/likec4/assets/55560119/055876bd-2e93-4027-90d4-2ccd62c66df7)
![likec4-2](https://github.com/likec4/likec4/assets/55560119/165cd2f9-2f1d-472d-b26a-2f5138b3b17a)
